# Importing Datasets

In [55]:
# Import libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [56]:
# importing Yelp dataset

data_yelp = pd.read_csv('yelp_labelled.txt', sep='\t',header=None)

In [57]:
data_yelp.head()
# review and sentiment
# 0-Negative, 1-Positive for positive review

0  1
0                           Wow... Loved this place.  1
1                                 Crust is not good.  0
2          Not tasty and the texture was just nasty.  0
3  Stopped by during the late May bank holiday of...  1
4  The selection on the menu was great and so wer...  1

In [58]:
# Assign column names

columan_name = ['Review', 'Sentiment']
data_yelp.columns = columan_name

In [59]:
data_yelp.head()

Review  Sentiment
0                           Wow... Loved this place.          1
1                                 Crust is not good.          0
2          Not tasty and the texture was just nasty.          0
3  Stopped by during the late May bank holiday of...          1
4  The selection on the menu was great and so wer...          1

In [60]:
data_yelp.shape
# 1000 rows, 2 columns

(1000, 2)

In [61]:
# importing Amazon dataset

data_amazon = pd.read_csv('amazon_cells_labelled.txt',sep='\t',header=None)
data_amazon.head()

# 0-Negative, 1-Positive for positive review

0  1
0  So there is no way for me to plug it in here i...  0
1                        Good case, Excellent value.  1
2                             Great for the jawbone.  1
3  Tied to charger for conversations lasting more...  0
4                                  The mic is great.  1

In [62]:
# re-naming the columns
data_amazon.columns = columan_name
data_amazon.head()

Review  Sentiment
0  So there is no way for me to plug it in here i...          0
1                        Good case, Excellent value.          1
2                             Great for the jawbone.          1
3  Tied to charger for conversations lasting more...          0
4                                  The mic is great.          1

In [63]:
data_amazon.shape

(1000, 2)

In [64]:
# importing IMDB dataset

data_imdb = pd.read_csv('imdb_labelled.txt',sep='\t',header=None)
data_imdb.head()

0  1
0  A very, very, very slow-moving, aimless movie ...  0
1  Not sure who was more lost - the flat characte...  0
2  Attempting artiness with black & white and cle...  0
3       Very little music or anything to speak of.    0
4  The best scene in the movie was when Gerardo i...  1

In [65]:
# re-naming the columns
data_imdb.columns = columan_name
data_imdb.head()

Review  Sentiment
0  A very, very, very slow-moving, aimless movie ...          0
1  Not sure who was more lost - the flat characte...          0
2  Attempting artiness with black & white and cle...          0
3       Very little music or anything to speak of.            0
4  The best scene in the movie was when Gerardo i...          1

In [66]:
data_imdb.shape

(748, 2)

#### i. Append all the data in a single dataframe

In [67]:
data = data_yelp._append([data_amazon, data_imdb],ignore_index=True)

In [68]:
data.shape

(2748, 2)

In [69]:
data.head()

Review  Sentiment
0                           Wow... Loved this place.          1
1                                 Crust is not good.          0
2          Not tasty and the texture was just nasty.          0
3  Stopped by during the late May bank holiday of...          1
4  The selection on the menu was great and so wer...          1

#### ii. Check distribution of sentiments

In [70]:
data['Sentiment'].value_counts()

# 1386 positive reviews (1)
# 1362 Negative reviews (0)

Sentiment
1    1386
0    1362
Name: count, dtype: int64

In [71]:
# check for null values
data.isnull().sum()

# no null values in the data

Review       0
Sentiment    0
dtype: int64

# Data Cleaning 

In [72]:
## Here we will remove stopwords, punctuations
## as well as we will apply lemmatization

### i. imports, punct, stopwords

In [73]:
# import libraries

import string
from spacy.lang.en.stop_words import STOP_WORDS

In [74]:
# Punctuations available

punct = string.punctuation
punct

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [75]:
# list of stop words available

stopwords = list(STOP_WORDS) # list of stopwords


### ii. creating a function for data cleaning 

In [76]:
import spacy 
nlp = spacy.load('en_core_web_sm')

def text_data_cleaning(sentence):
  doc = nlp(sentence)

  tokens = [] # list of tokens
  for token in doc:
    if token.lemma_ != "-PRON-":
      temp = token.lemma_.lower().strip()
    else:
      temp = token.lower_
    tokens.append(temp)
  
  cleaned_tokens = []
  for token in tokens:
    if token not in stopwords and token not in punct:
      cleaned_tokens.append(token)
  return cleaned_tokens

In [77]:
# if root form of that word is not pronoun then it is going to convert that into lower form
# and if that word is a proper noun, then we are directly taking lower form, because there is no lemma for proper noun

In [78]:
# trial: remove all stopwords and punctuations

text_data_cleaning("Hello all, It's a beautiful day outside there!")

['hello', 'beautiful', 'day', 'outside']

### iii. Vectorization Feature Engineering (TF-IDF)

In [79]:

# TF-IDF is a feature available cleaning the data.
# We don't need to define separate function as we did above.


In [80]:
from sklearn.svm import LinearSVC
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline

In [81]:
# using TfidfVectorizer class from sklearn library - we will convert all our original records/reviews into numbers
# tfidf uses formula to know which word has how much importance
# scoring will be given
# how many times a term (t) occurs in a document (d)
# inverse document frequency x (idf) 
# rare words - high weightage

tfidf = TfidfVectorizer(tokenizer=text_data_cleaning)
# tokenizer=text_data_cleaning, tokenization will be done according to this function

# TfidfVectorizer will:
#    1. be applied to text_data_cleaning function
#    2. tfidf formula will be applied to get tfidf score for each individual term in different documents

In [82]:

# creating support vector machine classifier
classifier = LinearSVC()

# Train the model

In [83]:
# We have data available with us
# We have machine learning algorithm available with us

# Now, we have to train this model

### i. Splitting the dataset into the Train and Test set

In [84]:

from sklearn.model_selection import train_test_split

x = data['Review']
y = data['Sentiment']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0) # 20% = testing

In [85]:

x_train.shape, x_test.shape
# 2198 samples in training dataset and 550 in test dataset

((2198,), (550,))

In [86]:

x_train.head()

2572    An Italian reviewer called this "a small, grea...
526                          And it was way to expensive.
1509    As an earlier review noted, plug in this charg...
144     Nice blanket of moz over top but i feel like t...
2483    The film gives meaning to the phrase, "Never i...
Name: Review, dtype: object

### ii. Fit the x_train and y_train

In [87]:

clf = Pipeline([('tfidf',tfidf), ('clf',classifier)])
# it will first do vectorization and then it will do classification

In [88]:

# start training the data
clf.fit(x_train, y_train)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\feature_extraction\text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\svm\_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(


Pipeline(steps=[('tfidf',
                 TfidfVectorizer(tokenizer=<function text_data_cleaning at 0x000002228E009DA0>)),
                ('clf', LinearSVC())])

In [89]:

# in this we don't need to prepare the dataset for testing(x_test)


# Predict the Test set results

In [99]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [100]:

# apply prediction on our test dataset
y_pred = clf.predict(x_test)

In [92]:
# since it is a binary classification problem: 2x2 matrix

# confusion_matrix
confusion_matrix(y_test, y_pred)

# 201 + 221 = right prediction
# 50 + 78 = incorrect predictions


array([[201,  78],
       [ 50, 221]], dtype=int64)

In [93]:

# classification_report - detailed report
print(classification_report(y_test, y_pred))

# we are getting almost 77% accuracy


              precision    recall  f1-score   support

           0       0.80      0.72      0.76       279
           1       0.74      0.82      0.78       271

    accuracy                           0.77       550
   macro avg       0.77      0.77      0.77       550
weighted avg       0.77      0.77      0.77       550



In [94]:
accuracy_score(y_test, y_pred)
# 76% accuracy

0.7672727272727272

#### TESTING 

In [96]:

clf.predict(["Wow, I am learning Natural Language Processing in fun fashion!"])
# output is 1, that means review is positive


array([1], dtype=int64)

In [97]:

clf.predict(["It's hard to learn new things!"])
# output is 0, that means review is Negative


array([0], dtype=int64)